### ISSUE TITLE
Calender file blank

### ISSUE THREAD

**Issue by daemenseth** [microsoft/adaptive_cloud_community#7]
Is is possible that the calender file is blank.
When are the next meetings?

**Comment by johnwildes** [comment]
@likamrat @kianaharris4  the ICS link in the readme doesn't work.  When I click on it, it takes me to my personal onedrive with an error that states the file has been removed, moved or you do not have access to it.  

Would love to join the meeting but can't get the teams info because the ics file is missing.

**Comment by Karl-WE** [comment]
Can confirm.

**Comment by psinnathurai** [comment]
Same for me.

**Comment by Karl-WE** [comment]
fixed with #15 #16 , thank you @thomasmaurer
